name: Release on tag creation

on:
  push:
    tags:
      - "*"

jobs:
  release-from-tag:
    permissions:
      contents: write
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install all dependencies
          pip install pyinstaller  # Ensure PyInstaller is installed

      - name: Build EXE with PyInstaller
        run: pyinstaller -F --add-data="templates;templates" --add-data="helper.py;." main.py

      - name: Rename EXE
        run: Rename-Item -Path dist\main.exe -NewName main.exe

      - name: Upload EXE as Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/my_app.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}